spring:
  config.activate.on-profile: "dev"
  flyway:
    enabled: true
    locations: classpath:db/migration/MySQL
  jpa:
    defer-datasource-initialization: false
    hibernate.ddl-auto: none
  datasource:
    url: "jdbc:mysql://localhost/DbMySql"
    username: "iksad"
    password: "1234"