spring:
  config.activate.on-profile: "common"
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.batch_size: 1000

logging.level:
  root: INFO
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  me.iksadnorth.insta: TRACE

cors:
  allowed-url:
    http://localhost:8090, 
    http://192.168.25.3:8090

download:
  image:
    trg-dir: images
