spring:
  config.activate.on-profile: "test"
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
  datasource:
    url: "jdbc:h2:mem:test_mem"
    username: "iksad"
    password: "1234"
  h2.console:
    enabled: true
    path: /h2
sql.init.mode: always
