spring:
  config.activate.on-profile: "test"
  flyway:
    enabled: true
    locations: classpath:db/migration/h2
  jpa:
    defer-datasource-initialization: false
    hibernate.ddl-auto: none
  datasource:
    url: "jdbc:h2:mem:test_mem"
    username: "iksad"
    password: "1234"
  h2.console:
    enabled: true
    path: /h2
sql.init.mode: always
