spring.profiles.group:
  "test": "test, common"
  "dev": "dev, common"
  "prod": "prod, common"


---


spring:
  config.activate.on-profile: "common"
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true

logging.level:
  root: INFO
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  me.iksadnorth.insta: TRACE

jwt:
  secret-key: 00c89a1f936f93e5a83964f2c34e44195595f7cac271a7c4bee3cf85087043930bb082aa1705281f37c1bd282edcc8f9b6581018d01fcfcf60fa694416f6bf8a
  #  for a month
  expired-time-ms: 2592000000

cors:
  allowed-url:
    http://localhost:8090, 
    http://192.168.25.3:8090

download:
  image:
    trg-dir: src/main/resources/images


---


spring:
  config.activate.on-profile: "test"
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
  datasource:
    url: "jdbc:h2:mem:test_mem"
    username: "iksad"
    password: "1234"
  h2.console:
    enabled: true
    path: /h2
sql.init.mode: always


---


spring:
  config.activate.on-profile: "prod"
  jpa:
    hibernate.ddl-auto: validate
  datasource:
    url: "jdbc:mysql://localhost/DbMySql"
    username: "iksad"
    password: "1234"


---


spring:
  config.activate.on-profile: "dev"
  jpa:
    hibernate.ddl-auto: create
  datasource:
    url: "jdbc:mysql://localhost/DbMySql"
    username: "iksad"
    password: "1234"